### ISSUE TITLE
The Road to Bionic Support

### ISSUE THREAD

**Issue by ekristen** [teamdfir/sift#348]
This is the placeholder issue for moving to Ubuntu 18.04 Bionic for SIFT. This issue will get updated over time with more information as status as we make this transition. 

## Tasks

* [x] - Determine which packages do not install in 18.04
* [x] - Determine which python packages do not install in 18.04
* [x] - User Config has to be reworked for Gnome instead of Unity (most likely the heaviest lift exists here)

### Package Support

The general problem here is that packages are removed between distributions or their name changes. 

* [x] - dumbpig
* [x] - liblightgrep
  * Note: does not automatically compile on bionic, project hasn't been touched in years.
* [x] - pdftk
* [x] - powershell
* [x] - python-pytsk3
* [x] - wine

#### SIFT Maintained Forked Packages 

Ideally SIFT shouldn't or doesn't want to maintain any forks of packages and instead prefers to encourage developers of tools to ensure their tools are built for distribution, with that said these are the packages SIFT maintains a fork of.

**Note:** This list is currently short and incomplete as I'm building it from scratch during the move to Bionic so that I can remove old packages we no longer want to support a fork of.

* sleuthkit
* xmount
* volatility

## User Config

18.04 went to gnome, unfortunately unity and gnome are not similar so all user/config related scripts to build a consistent desktop environment have to be rewritten for 18.04

**Comment by joachimmetz** [comment]
> encourage developers of tools to ensure their tools are built for distribution

This is somewhat (unrealistic) wishful thinking. Deployment is a different skill set than development. Also what is the value of a "distribution" when the developers are doing all the work? **Any time spent by a project on deployment takes a way from development and actually improving.** 

There are also more distributions than project developers/maintainers for most DFIR FOSS projects.

I understand that maintaining SIFT is a burden that seems to be largely on your shoulders but I opt that other people get involved, also seeing SANS and other educators seems to heavy rely on it.

**Comment by Fetchered** [comment]
I am interested in helping out. I don't have any salt experience except end-user, however I have plenty of experience in just about everything else where it counts. If you're interested, my assistance is available for this.

**Comment by ekristen** [comment]
Awesome. I need to spend some time getting what I’ve done already up and put some instructions together for people such as yourself looking to assist.

**Comment by q2dg** [comment]
Well, we are in April 2019 already...so maybe this issue could wait until Ubuntu 20.04 :-/

**Comment by ekristen** [comment]
We are close to this. It’s coming with a bunch of other things too. 20.04 wont happen for at least 4-6 months after its release. A lot goes into making it all work together. 18.04 changed a lot, this is part of the delay.

**Comment by ekristen** [comment]
We are down to 44 of 251 that need a bit of work to get onto 18.04. We are taking the necessary steps to make rebuilding for 20.04 easier at the same time. Some are easy fixes, some are not. Once all packages are taken care of, we'll begin community testing.

The next step is all the custom UI changes and user config tweaks that are done. Unfortunately this is taking a bit longer than expected due to the change from unity back to gnome.

**Comment by sanjmishra** [comment]
in Bionic 'python-software-properties' is not installing. While searching on the internet I found that I have to install 'software-properties-common' instead and it would work. But it seems the package has info for searching 'python-software-properties'. Is there some configuration changes required to get it running on Bionic ? Or I have to wait for fixes for Bionic to get SIFT up and running in Bionic?

**Comment by ekristen** [comment]
If you follow the instructions on the https://github.com/teamdfir/sift-saltstack repo you'll get initial 18.04 support.

**Comment by ekristen** [comment]
The latest pre-release now has 18.04 support.

**Comment by Fetchered** [comment]
Had a chance to install, found a minor/fixable issue with rekall during the install. Would you like the issues posted here (for 18.04) or in with the general issues?

**Comment by ekristen** [comment]
New issue please.

**Comment by Fetchered** [comment]
Done.
